%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% @AutoGenerated
%
% Filename: Step3_RandomSampling.m
% Author: Alper Ender
% Date: November 2017
% Description: Randomly samples the data from the individual files. Takes
% only inbox emails that have correct headers
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\

clc;

%% Setup

% TOTAL EMAILS: 490854
% TOTAL EMAIL ACCOUNTS: 149

% Folder location
FOLDER_LOCATION = folder_system.IndividualFiles;

% Insert desired maximum number of samples to create here
TOTAL_SAMPLE = 6000;

% Insert the file directory location here
FILE_LOCATION = folder_system.Sampling;

% Opens the file to write to
write_FID = fopen([FILE_LOCATION 'tmp.csv'],'w');

%% Calculations

% Total emails and number of accounts
total_emails = 490854;
total_email_accounts = 149;

% Obtains the number of samples to take from each account
samples_per_account = floor(TOTAL_SAMPLE / total_email_accounts)

% Initializing Variables
all_emails = cell(samples_per_account * total_email_accounts,1);
ae_counter = 1;

%% Obtaining samples

email_samples = {};

% Change to the folder location
cd(FOLDER_LOCATION)

% Getting all the students in the folder
students = dir('*.csv');

% Iterating through all the csv files
for i = 1:length(students)
    
    % The name of the student
    name = students(i).name;
    fprintf('Importing %s...\n', name);
    
    % Opening the file
    FID = fopen(name);
    
    % Resetting the variables
    student_emails = {};
    count = 1;
    
    % Obtaining all the emails from the file
    while ~feof(FID)
        
        line = fgetl(FID);
        tok = split(line,',');
        
        % Looking at only inbox emails
        rule1 = contains(lower(line), '_inbox');
        
        % Looking at emails with correct headers
        rule2 = ~contains(tok{5},'.com');
        rule3 = ~contains(tok{5}, 'sion: 1.0');
        rule4 = ~contains(tok{4}, 'ject:');
        
        % If the rules are satisfied, then append to the email cell
        if rule1 & rule2 & rule3 & rule4 
            student_emails{count, 1} = line;
            count = count + 1;
        end
        
    end
    
    % Obtain the size of all the emails
    [r,c] = size(student_emails);
    
    % Create a random set of numbers
    r_values = randperm(r);
    
    % Take the lesser between r and and samples per student
    if samples_per_account > r
        ind = r;
    else
        ind = samples_per_account;
    end
    
    % Take the first n numbers
    r_values_person = r_values(1:ind);
    
    % Take the first n eamils
    r_emails = student_emails(r_values_person);
    
    % Append the emails to the file
    for j = 1:length(r_emails)
        if isempty(r_emails{j})
            continue
        end
        
        % Do not put a line break at the end of the file
        if i == length(students) & j == length(r_emails)
            fprintf(write_FID, '%s', r_emails{j});
        else
            fprintf(write_FID, '%s\n', r_emails{j});
        end
    end
    
    fclose(FID);
    
end

fclose('all');

%% Rename the file appropriately

% Read the file
FID = fopen([FILE_LOCATION 'tmp.csv'], 'r');

counter = 0;

% Count the number of lines
while ~feof(FID)
    fgetl(FID);
    counter = counter + 1;
end

% Close the file
fclose(FID);

% Rename the file with the correct number of samples
movefile([FILE_LOCATION 'tmp.csv'], [FILE_LOCATION 'Samples_' int2str(counter) '.csv'])

